# Generated by Django 5.0.6 on 2024-06-07 20:30

import django.db.models.deletion
from django.db import migrations, models

def create_default_category(apps, schema_editor):
    Category = apps.get_model('crud', 'Category')
    if not Category.objects.filter(id=1).exists():
        Category.objects.create(id=1, name='Default Category')

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crud.category'),
        ),
        migrations.RunPython(create_default_category),
    ]
